package com.phq9_final.phq9final;

import java.lang.Number;


rule "PreScreenTree_00"
	dialect "mvel"
	ruleflow-group "PreScreenRule"
	when 
		PatientP : PatientParticular(marital_status matches "Separated")
	then 
		PreScreenR $var0 = new PreScreenR();
		$var0.setPreScreenResult( true );
		insert( $var0 );
end
rule "PreScreenTree_01"
	dialect "mvel"
	ruleflow-group "PreScreenRule"
	when 
		PatientP : PatientParticular(marital_status matches "Widowed")
	then 
		PreScreenR $var0 = new PreScreenR();
		$var0.setPreScreenResult( true );
		insert( $var0 );
end
rule "PreScreenTree_02"
	dialect "mvel"
	ruleflow-group "PreScreenRule"
	when 
		PatientP : PatientParticular(marital_status not matches "Widowed", marital_status not matches "Separated", race not matches "Others", age not matches "18-34", gender matches "Female", chronic matches "Yes")
	then 
		PreScreenR $var0 = new PreScreenR();
		$var0.setPreScreenResult( true );
		insert( $var0 );
end
rule "PreScreenTree_03"
	dialect "mvel"
	ruleflow-group "PreScreenRule"
	when 
		PatientP : PatientParticular(marital_status not matches "Widowed", marital_status not matches "Separated", race not matches "Others", age matches "18-34")
	then 
		PreScreenR $var0 = new PreScreenR();
		$var0.setPreScreenResult( true );
		insert( $var0 );
end
rule "PreScreenTree_04"
	dialect "mvel"
	ruleflow-group "PreScreenRule"
	when 
		PatientP : PatientParticular(marital_status not matches "Widowed", marital_status not matches "Separated", race matches "Others")
	then 
		PreScreenR $var0 = new PreScreenR();
		$var0.setPreScreenResult( true );
		insert( $var0 );
end
