package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PHQ2R implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PHQ2R() {
    }




}