package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PHQ9R implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PHQ9R() {
    }




}