package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PhqCheck implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.phq9_final.phq9final.PHQ2Q PHQ2Qa;

	private com.phq9_final.phq9final.PHQ9Q PHQ9Qa;

	private java.lang.Integer inBlue;

	public PhqCheck() {
	}

	public int getPHQ2QaInBlue() {
		private java.lang.Integer inBlue2 = 0;
		if (PHQ2Qa.getPHQQ1() >= 2) {
			inBlue2++;
		}
		if (PHQ2Qa.getPHQQ2() >= 2) {
			inBlue2++;
		}

		return 0;
	}

	public int getPHQ9QaInBlue() {
		private java.lang.Integer inBlue9 = 0;
		if (PHQ9Qa.getPHQQ3() >= 2) {
			inBlue9++;
		}
		if (PHQ9Qa.getPHQQ4() >= 2) {
			inBlue9++;
		}
		if (PHQ9Qa.getPHQQ5() >= 2) {
			inBlue9++;
		}
		if (PHQ9Qa.getPHQQ6() >= 2) {
			inBlue9++;
		}
		if (PHQ9Qa.getPHQQ7() >= 2) {
			inBlue9++;
		}
		if (PHQ9Qa.getPHQQ8() >= 2) {
			inBlue9++;
		}
		if (PHQ9Qa.getPHQQ9() >= 1) {
			inBlue9++;
		}

		return 0;
	}

	public int getTotalInBlue() {

        this.inBlue=getPHQ2QaInBlue() + getPHQ9QaInBlue();
		return 0;
	}

	public com.phq9_final.phq9final.PHQ2Q getPHQ2Qa() {
		return this.PHQ2Qa;
	}

	public void setPHQ2Qa(com.phq9_final.phq9final.PHQ2Q PHQ2Qa) {
		this.PHQ2Qa = PHQ2Qa;
	}

	public com.phq9_final.phq9final.PHQ9Q getPHQ9Qa() {
		return this.PHQ9Qa;
	}

	public void setPHQ9Qa(com.phq9_final.phq9final.PHQ9Q PHQ9Qa) {
		this.PHQ9Qa = PHQ9Qa;
	}

	public java.lang.Integer getInBlue() {
		return this.inBlue;
	}

	public void setInBlue(java.lang.Integer inBlue) {
		this.inBlue = inBlue;
	}

	public PhqCheck(com.phq9_final.phq9final.PHQ2Q PHQ2Qa,
			com.phq9_final.phq9final.PHQ9Q PHQ9Qa, java.lang.Integer inBlue) {
		this.PHQ2Qa = PHQ2Qa;
		this.PHQ9Qa = PHQ9Qa;
		//this.inBlue = inBlue;
	}

}